### ISSUE TITLE
UI improvements

### ISSUE THREAD

**Issue by OneLiL05** [CoderSaty/FirstProjects#49]
Hey, can I improve UI of your website

There is a list of my improvements: 

---

- add dark theme and `CSS variables` for it;
- Put all `css` files into css directory and the same thing with `html` without `index.html`;
- add `.gitignore` file;
- add some improvements with buttons, typography and so on;
- add design system and documentation, if you would like;
- improve accesability at your site

May I do it?

**Comment by OneLiL05** [comment]
Hey, now I have some list of improvements, I will plan do it, if you like:
- put all `js`from `script` tag to the separate file;
- add linter for example `editorcofig` for better code style;
- add separate files for adaptive styles, and connect it to the `html` in better way. I know how to load styles more efectively.

**Comment by CoderSaty** [comment]
Hi, @OneLiL05 Thanks a lot for the previous Pull request you can go ahead with all these improvements if you are still interested, and once again sorry for the late reply.

**Comment by OneLiL05** [comment]
@CoderSaty, I have some questions about your project, you use icon fonts, but it isn't good for site rendering, and accesability, can I add my icons, that are already setted up for prefomance, I will add docs how to use them in the next PR (pull request), if you like my proposal. Also I have good idea about code style at this project, if you like, I add test that would check all PR's and say follow they code style or not, I also can add docs about it.
